package javaapplication5;
public class Login extends javax.swing.JFrame {

/* Creates new form Login */
public Login() 
  {
    initComponents();
  }

/*** This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor.*/
@SuppressWarnings(&quot;unchecked&quot;)
// &lt;editor-fold defaultstate=&quot;collapsed&quot; desc=&quot;Generated Code&quot;&gt;
private void initComponents()
  {
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    jLabel1.setFont(new java.awt.Font(&quot;Segoe UI&quot;, 1, 24)); // NOI18N
    jLabel1.setText(&quot;STUDENT REGISTRATION FORM&quot;);
    jLabel2.setFont(new java.awt.Font(&quot;Segoe UI&quot;, 1, 18)); // NOI18N
    jLabel2.setText(&quot;LOGIN FORM&quot;);
    jLabel3.setFont(new java.awt.Font(&quot;Segoe UI&quot;, 1, 14)); // NOI18N
    jLabel3.setText(&quot;USERNAME:&quot;);
    jTextField1.addActionListener(new java.awt.event.ActionListener() 
                                  {
                                    public void actionPerformed(java.awt.event.ActionEvent evt) 
                                    {
                                      jTextField1ActionPerformed(evt);
                                    }
                                  });
    jLabel4.setFont(new java.awt.Font(&quot;Segoe UI&quot;, 1, 14)); // NOI18N
    jLabel4.setText(&quot;PASSWORD:&quot;);
    jTextField2.addActionListener(new java.awt.event.ActionListener()
                                  {
                                    public void actionPerformed(java.awt.event.ActionEvent evt)
                                    {
                                      jTextField2ActionPerformed(evt);
                                    }
                                  });
    jButton1.setFont(new java.awt.Font(&quot;Segoe UI&quot;, 1, 14)); // NOI18N
    jButton1.setText(&quot;SUBMIT&quot;);
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addGap(142, 142, 142)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                      .addComponent(jLabel4)
                                                                      .addComponent(jLabel3))
                                                            .addGap(29, 29, 29)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                      .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                      .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addGap(188, 188, 188)
                                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139,javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addGap(230, 230, 230)
                                                            .addComponent(jButton1))
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addGap(123, 123, 123)
                                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400,javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(61, Short.MAX_VALUE)));
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40,javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32,javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                          .addComponent(jLabel4)
                          .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jButton1)
                .addContainerGap(132, Short.MAX_VALUE)));
    pack();
  }
  // &lt;/editor-fold&gt;
private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) 
  {
    // TODO add your handling code here:
  }
private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)
  {
    // TODO add your handling code here:
  }

/**
* @param args the command line arguments
*/
public static void main(String args[]) 
  {
                 /* Set the Nimbus look and feel */
                 //&lt;editor-fold defaultstate=&quot;collapsed&quot; desc=&quot; Look and feel setting code (optional) &quot;&gt;
                 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html */
try
  {
    for (javax.swing.UIManager.LookAndFeelInfo info :
         javax.swing.UIManager.getInstalledLookAndFeels()) 
    {
      if (&quot;Nimbus&quot;.equals(info.getName()))
      {
        javax.swing.UIManager.setLookAndFeel(info.getClassName());
      break;
      }
    }
  }
catch (ClassNotFoundException ex)
  {
    java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
catch (InstantiationException ex) 
  {
    java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
catch (IllegalAccessException ex)
  {
    java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
catch (javax.swing.UnsupportedLookAndFeelException ex)
  {
    java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
//&lt;/editor-fold&gt;

/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() {
  public void run() {
new Login().setVisible(true);
}
});
}

// Variables declaration - do not modify
private javax.swing.JButton jButton1;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel4;
private javax.swing.JTextField jTextField1;
private javax.swing.JTextField jTextField2;
// End of variables declaration
}
          
