package student_feedback;
public class Student_Form extends javax.swing.JFrame {
         /** Creates new form Student_Form*/
public Student_Form() {
initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jRadioButton41 = new javax.swing.JRadioButton();
        jRadioButton42 = new javax.swing.JRadioButton();
        jRadioButton43 = new javax.swing.JRadioButton();
        jRadioButton44 = new javax.swing.JRadioButton();
        jRadioButton45 = new javax.swing.JRadioButton();
        jRadioButton46 = new javax.swing.JRadioButton();
        jRadioButton47 = new javax.swing.JRadioButton();
        jRadioButton48 = new javax.swing.JRadioButton();
        jRadioButton49 = new javax.swing.JRadioButton();
        jRadioButton50 = new javax.swing.JRadioButton();
        jRadioButton51 = new javax.swing.JRadioButton();
        jRadioButton52 = new javax.swing.JRadioButton();
        jRadioButton53 = new javax.swing.JRadioButton();
        jRadioButton54 = new javax.swing.JRadioButton();
        jRadioButton55 = new javax.swing.JRadioButton();
        jRadioButton56 = new javax.swing.JRadioButton();
        jRadioButton57 = new javax.swing.JRadioButton();
        jRadioButton58 = new javax.swing.JRadioButton();
        jRadioButton62 = new javax.swing.JRadioButton();
        jRadioButton63 = new javax.swing.JRadioButton();
        jRadioButton64 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

jLabel21.setText("jLabel21");

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
setBackground(new java.awt.Color(51, 204, 0));

jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
jLabel1.setText("Student Feedback Registration Form");

jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
jLabel2.setText("Fill out the form with honestly");

jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel3.setText("Student Name:");

jTextField1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jTextField1ActionPerformed(evt);
            }
        });

jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel4.setText("8 - Digit Student ID:");

jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel5.setText("Student E-mail ID:");

jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel6.setText("Course Name:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "BA.Tamil", "BA.English", "B.Sc.Maths", "B.sc.Physics", "B.Sc.Chemistry", "B.Sc.Botany", "B.Sc.Zoology", "B.Sc.Computer Science", "B.Sc.Information Technology", "BCA", "MCA", "MBA", " " }));
jComboBox1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jComboBox1ActionPerformed(evt);
            }
        });

jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel7.setText("Gender :");

jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel8.setText("Instructor Name:");

jTextField5.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jTextField5ActionPerformed(evt);
            }
        });

jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel9.setText("Instructor Feedback:");

jLabel10.setBackground(new java.awt.Color(255, 255, 255));
jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel10.setText("Receive syllabus & instructions at first");

jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel11.setText("Course objectives started clearly ");

jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel12.setText("Material presented in class matches syllabus");

jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel13.setText("Instructor responded questions");

jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel14.setText("Instructor demonstrates adequate knowledge of course");

jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel15.setText("Instructor uses appropriate teaching methods");

jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel16.setText("Instructor returns papers & tests promptly");

jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel17.setText("Class time is used efficient");

jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel18.setText("Instructor is helpful");

jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel19.setText("Instructor is well prepared");

jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel20.setText("Instructor overall teaching");

jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
jLabel22.setText("Recommed the class");

jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Male", "Female", "Others" }));

jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
jLabel23.setText("Strongly Agree");

buttonGroup1.add(jRadioButton1);
jRadioButton1.setText("jRadioButton1");

buttonGroup1.add(jRadioButton2);
jRadioButton2.setText("jRadioButton1");

buttonGroup1.add(jRadioButton3);
jRadioButton3.setText("jRadioButton1");

jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
jLabel24.setText("Agree");

jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
jLabel25.setText("Neutral");

jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
jLabel26.setText("Disaagree");

jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
jLabel27.setText("Strongly Disagree");

buttonGroup1.add(jRadioButton4);
jRadioButton4.setText("jRadioButton1");

buttonGroup1.add(jRadioButton5);
jRadioButton5.setText("jRadioButton1");

buttonGroup2.add(jRadioButton6);
jRadioButton6.setText("jRadioButton1");

buttonGroup3.add(jRadioButton7);
jRadioButton7.setText("jRadioButton1");

buttonGroup4.add(jRadioButton8);
jRadioButton8.setText("jRadioButton1");

buttonGroup5.add(jRadioButton9);
jRadioButton9.setText("jRadioButton1");

buttonGroup6.add(jRadioButton10);
jRadioButton10.setText("jRadioButton1");

buttonGroup7.add(jRadioButton11);
jRadioButton11.setText("jRadioButton1");

buttonGroup8.add(jRadioButton12);
jRadioButton12.setText("jRadioButton1");

buttonGroup9.add(jRadioButton13);
jRadioButton13.setText("jRadioButton1");

buttonGroup10.add(jRadioButton14);
jRadioButton14.setText("jRadioButton1");

buttonGroup11.add(jRadioButton15);
jRadioButton15.setText("jRadioButton1");

buttonGroup12.add(jRadioButton17);
jRadioButton17.setText("jRadioButton1");

buttonGroup2.add(jRadioButton18);
jRadioButton18.setText("jRadioButton1");

buttonGroup2.add(jRadioButton19);
jRadioButton19.setText("jRadioButton1");

buttonGroup2.add(jRadioButton20);
jRadioButton20.setText("jRadioButton1");

buttonGroup3.add(jRadioButton21);
jRadioButton21.setText("jRadioButton1");

buttonGroup3.add(jRadioButton22);
jRadioButton22.setText("jRadioButton1");

buttonGroup2.add(jRadioButton23);
jRadioButton23.setText("jRadioButton1");
jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton23ActionPerformed(evt);
            }
        });

buttonGroup3.add(jRadioButton24);
jRadioButton24.setText("jRadioButton1");
jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton24ActionPerformed(evt);
            }
        });

buttonGroup3.add(jRadioButton25);
jRadioButton25.setText("jRadioButton1");
jRadioButton25.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton25ActionPerformed(evt);
            }
        });

buttonGroup4.add(jRadioButton26);
jRadioButton26.setText("jRadioButton1");
jRadioButton26.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton26ActionPerformed(evt);
            }
        });

buttonGroup4.add(jRadioButton27);
jRadioButton27.setText("jRadioButton1");
jRadioButton27.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton27ActionPerformed(evt);
            }
        });

buttonGroup4.add(jRadioButton28);
jRadioButton28.setText("jRadioButton1");
jRadioButton28.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton28ActionPerformed(evt);
            }
        });

buttonGroup5.add(jRadioButton29);
jRadioButton29.setText("jRadioButton1");
jRadioButton29.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton29ActionPerformed(evt);
            }
        });

buttonGroup5.add(jRadioButton30);
jRadioButton30.setText("jRadioButton1");
jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton30ActionPerformed(evt);
            }
        });

buttonGroup4.add(jRadioButton31);
jRadioButton31.setText("jRadioButton1");
jRadioButton31.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton31ActionPerformed(evt);
            }
        });

buttonGroup5.add(jRadioButton32);
jRadioButton32.setText("jRadioButton1");
jRadioButton32.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton32ActionPerformed(evt);
            }
        });

buttonGroup5.add(jRadioButton33);
jRadioButton33.setText("jRadioButton1");
jRadioButton33.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton33ActionPerformed(evt);
            }
        });

buttonGroup6.add(jRadioButton34);
jRadioButton34.setText("jRadioButton1");
jRadioButton34.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton34ActionPerformed(evt);
            }
        });

buttonGroup8.add(jRadioButton35);
jRadioButton35.setText("jRadioButton1");
jRadioButton35.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton35ActionPerformed(evt);
            }
        });

buttonGroup7.add(jRadioButton36);
jRadioButton36.setText("jRadioButton1");
jRadioButton36.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton36ActionPerformed(evt);
            }
        });

buttonGroup9.add(jRadioButton37);
jRadioButton37.setText("jRadioButton1");
jRadioButton37.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton37ActionPerformed(evt);
            }
        });

buttonGroup10.add(jRadioButton38);
jRadioButton38.setText("jRadioButton1");
jRadioButton38.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton38ActionPerformed(evt);
            }
        });

buttonGroup11.add(jRadioButton39);
jRadioButton39.setText("jRadioButton1");
jRadioButton39.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton39ActionPerformed(evt);
            }
        });

buttonGroup12.add(jRadioButton40);
jRadioButton40.setText("jRadioButton1");
jRadioButton40.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton40ActionPerformed(evt);
            }
        });

buttonGroup6.add(jRadioButton41);
jRadioButton41.setText("jRadioButton1");
jRadioButton41.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton41ActionPerformed(evt);
            }
        });

buttonGroup7.add(jRadioButton42);
jRadioButton42.setText("jRadioButton1");
jRadioButton42.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton42ActionPerformed(evt);
            }
        });

buttonGroup8.add(jRadioButton43);
jRadioButton43.setText("jRadioButton1");
jRadioButton43.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton43ActionPerformed(evt);
            }
        });

buttonGroup9.add(jRadioButton44);
jRadioButton44.setText("jRadioButton1");
jRadioButton44.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton44ActionPerformed(evt);
            }
        });

buttonGroup10.add(jRadioButton45);
jRadioButton45.setText("jRadioButton1");
jRadioButton45.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton45ActionPerformed(evt);
            }
        });

buttonGroup11.add(jRadioButton46);
jRadioButton46.setText("jRadioButton1");
jRadioButton46.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton46ActionPerformed(evt);
            }
        });

buttonGroup12.add(jRadioButton47);
jRadioButton47.setText("jRadioButton1");
jRadioButton47.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton47ActionPerformed(evt);
            }
        });

buttonGroup6.add(jRadioButton48);
jRadioButton48.setText("jRadioButton1");
jRadioButton48.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton48ActionPerformed(evt);
            }
        });

buttonGroup8.add(jRadioButton49);
jRadioButton49.setText("jRadioButton1");
jRadioButton49.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton49ActionPerformed(evt);
            }
        });

buttonGroup7.add(jRadioButton50);
jRadioButton50.setText("jRadioButton1");
jRadioButton50.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton50ActionPerformed(evt);
            }
        });

buttonGroup9.add(jRadioButton51);
jRadioButton51.setText("jRadioButton1");
jRadioButton51.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton51ActionPerformed(evt);
            }
        });

buttonGroup10.add(jRadioButton52);
jRadioButton52.setText("jRadioButton1");
jRadioButton52.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton52ActionPerformed(evt);
            }
        });

buttonGroup12.add(jRadioButton53);
jRadioButton53.setText("jRadioButton1");
jRadioButton53.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton53ActionPerformed(evt);
            }
        });

buttonGroup11.add(jRadioButton54);
jRadioButton54.setText("jRadioButton1");
jRadioButton54.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton54ActionPerformed(evt);
            }
        });

buttonGroup6.add(jRadioButton55);
jRadioButton55.setText("jRadioButton1");
jRadioButton55.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton55ActionPerformed(evt);
            }
        });

buttonGroup7.add(jRadioButton56);
jRadioButton56.setText("jRadioButton1");
jRadioButton56.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton56ActionPerformed(evt);
            }
        });

buttonGroup12.add(jRadioButton57);
jRadioButton57.setText("jRadioButton1");
jRadioButton57.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton57ActionPerformed(evt);
            }
        });

buttonGroup8.add(jRadioButton58);
jRadioButton58.setText("jRadioButton1");
jRadioButton58.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton58ActionPerformed(evt);
            }
        });

buttonGroup11.add(jRadioButton62);
jRadioButton62.setText("jRadioButton1");
jRadioButton62.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton62ActionPerformed(evt);
            }
        });

buttonGroup10.add(jRadioButton63);
jRadioButton63.setText("jRadioButton1");
jRadioButton63.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton63ActionPerformed(evt);
            }
        });

buttonGroup9.add(jRadioButton64);
jRadioButton64.setText("jRadioButton1");
jRadioButton64.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEventevt) {
jRadioButton64ActionPerformed(evt);
            }
        });

jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
jButton1.setText("Submit");

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField2)
                                                .addComponent(jTextField3)
                                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField1)
                                                .addComponent(jTextField5)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                        .addComponent(jRadioButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jRadioButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jRadioButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jRadioButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jRadioButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel23)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel24)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel25)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel26)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel27)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton54, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton55, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jRadioButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jRadioButton57, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jRadioButton58, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jRadioButton62, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jRadioButton63, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jRadioButton64, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(88, 88, 88))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton1)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton2)
                                .addComponent(jRadioButton3)
                                .addComponent(jRadioButton4)
                                .addComponent(jRadioButton5)
                                .addComponent(jRadioButton1))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jLabel24)
                        .addComponent(jLabel25)
                        .addComponent(jLabel26)
                        .addComponent(jLabel27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton18)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton20)
                    .addComponent(jRadioButton23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton21)
                    .addComponent(jRadioButton22)
                    .addComponent(jRadioButton24)
                    .addComponent(jRadioButton25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton26)
                    .addComponent(jRadioButton27)
                    .addComponent(jRadioButton28)
                    .addComponent(jRadioButton31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton29)
                    .addComponent(jRadioButton30)
                    .addComponent(jRadioButton32)
                    .addComponent(jRadioButton33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton34)
                    .addComponent(jRadioButton41)
                    .addComponent(jRadioButton48)
                    .addComponent(jRadioButton55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton36)
                    .addComponent(jRadioButton42)
                    .addComponent(jRadioButton50)
                    .addComponent(jRadioButton56))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton35)
                    .addComponent(jRadioButton43)
                    .addComponent(jRadioButton49)
                    .addComponent(jRadioButton58))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jRadioButton13)
                    .addComponent(jRadioButton37)
                    .addComponent(jRadioButton44)
                    .addComponent(jRadioButton51)
                    .addComponent(jRadioButton64))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton38)
                    .addComponent(jRadioButton45)
                    .addComponent(jRadioButton52)
                    .addComponent(jRadioButton63))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton39)
                    .addComponent(jRadioButton46)
                    .addComponent(jRadioButton54)
                    .addComponent(jRadioButton62))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jRadioButton17)
                    .addComponent(jRadioButton40)
                    .addComponent(jRadioButton47)
                    .addComponent(jRadioButton53)
                    .addComponent(jRadioButton57))
                .addGap(20, 20, 20)
                .addComponent(jButton1))
        );

pack();
    }// </editor-fold>

private void jComboBox1ActionPerformed(java.awt.event.ActionEventevt) {                                           
        // TODO add your handling code here:
    }                                          

private void jTextField1ActionPerformed(java.awt.event.ActionEventevt) {                                            
        // TODO add your handling code here:
    }                                           

private void jRadioButton23ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton24ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton25ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton26ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton27ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton28ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton29ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton30ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton31ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton32ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton33ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton34ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton35ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton36ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton37ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton38ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton39ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton40ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton41ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton42ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton43ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton44ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton45ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton46ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton47ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton48ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton49ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton50ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton51ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton52ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton53ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton54ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton55ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton56ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton57ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton58ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton62ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton63ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jRadioButton64ActionPerformed(java.awt.event.ActionEventevt) {                                               
        // TODO add your handling code here:
    }                                              

private void jTextField5ActionPerformed(java.awt.event.ActionEventevt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
if ("Nimbus".equals(info.getName())) {
javax.swing.UIManager.setLookAndFeel(info.getClassName());
break;
                }
            }
        } catch (ClassNotFoundException ex) {
java.util.logging.Logger.getLogger(Student_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
java.util.logging.Logger.getLogger(Student_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
java.util.logging.Logger.getLogger(Student_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
java.util.logging.Logger.getLogger(Student_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
new Student_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
private javax.swing.ButtonGroup buttonGroup1;
private javax.swing.ButtonGroup buttonGroup10;
private javax.swing.ButtonGroup buttonGroup11;
private javax.swing.ButtonGroup buttonGroup12;
private javax.swing.ButtonGroup buttonGroup2;
private javax.swing.ButtonGroup buttonGroup3;
private javax.swing.ButtonGroup buttonGroup4;
private javax.swing.ButtonGroup buttonGroup5;
private javax.swing.ButtonGroup buttonGroup6;
private javax.swing.ButtonGroup buttonGroup7;
private javax.swing.ButtonGroup buttonGroup8;
private javax.swing.ButtonGroup buttonGroup9;
private javax.swing.JButton jButton1;
private javax.swing.JComboBox<String> jComboBox1;
private javax.swing.JComboBox<String> jComboBox2;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel10;
private javax.swing.JLabel jLabel11;
private javax.swing.JLabel jLabel12;
private javax.swing.JLabel jLabel13;
private javax.swing.JLabel jLabel14;
private javax.swing.JLabel jLabel15;
private javax.swing.JLabel jLabel16;
private javax.swing.JLabel jLabel17;
private javax.swing.JLabel jLabel18;
private javax.swing.JLabel jLabel19;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel20;
private javax.swing.JLabel jLabel21;
private javax.swing.JLabel jLabel22;
private javax.swing.JLabel jLabel23;
private javax.swing.JLabel jLabel24;
private javax.swing.JLabel jLabel25;
private javax.swing.JLabel jLabel26;
private javax.swing.JLabel jLabel27;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel4;
private javax.swing.JLabel jLabel5;
private javax.swing.JLabel jLabel6;
private javax.swing.JLabel jLabel7;
private javax.swing.JLabel jLabel8;
private javax.swing.JLabel jLabel9;
private javax.swing.JRadioButton jRadioButton1;
private javax.swing.JRadioButton jRadioButton10;
private javax.swing.JRadioButton jRadioButton11;
private javax.swing.JRadioButton jRadioButton12;
private javax.swing.JRadioButton jRadioButton13;
private javax.swing.JRadioButton jRadioButton14;
private javax.swing.JRadioButton jRadioButton15;
private javax.swing.JRadioButton jRadioButton17;
private javax.swing.JRadioButton jRadioButton18;
private javax.swing.JRadioButton jRadioButton19;
private javax.swing.JRadioButton jRadioButton2;
private javax.swing.JRadioButton jRadioButton20;
private javax.swing.JRadioButton jRadioButton21;
private javax.swing.JRadioButton jRadioButton22;
private javax.swing.JRadioButton jRadioButton23;
private javax.swing.JRadioButton jRadioButton24;
private javax.swing.JRadioButton jRadioButton25;
private javax.swing.JRadioButton jRadioButton26;
private javax.swing.JRadioButton jRadioButton27;
private javax.swing.JRadioButton jRadioButton28;
private javax.swing.JRadioButton jRadioButton29;
private javax.swing.JRadioButton jRadioButton3;
private javax.swing.JRadioButton jRadioButton30;
private javax.swing.JRadioButton jRadioButton31;
private javax.swing.JRadioButton jRadioButton32;
private javax.swing.JRadioButton jRadioButton33;
private javax.swing.JRadioButton jRadioButton34;
private javax.swing.JRadioButton jRadioButton35;
private javax.swing.JRadioButton jRadioButton36;
private javax.swing.JRadioButton jRadioButton37;
private javax.swing.JRadioButton jRadioButton38;
private javax.swing.JRadioButton jRadioButton39;
private javax.swing.JRadioButton jRadioButton4;
private javax.swing.JRadioButton jRadioButton40;
private javax.swing.JRadioButton jRadioButton41;
private javax.swing.JRadioButton jRadioButton42;
private javax.swing.JRadioButton jRadioButton43;
private javax.swing.JRadioButton jRadioButton44;
private javax.swing.JRadioButton jRadioButton45;
private javax.swing.JRadioButton jRadioButton46;
private javax.swing.JRadioButton jRadioButton47;
private javax.swing.JRadioButton jRadioButton48;
private javax.swing.JRadioButton jRadioButton49;
private javax.swing.JRadioButton jRadioButton5;
private javax.swing.JRadioButton jRadioButton50;
private javax.swing.JRadioButton jRadioButton51;
private javax.swing.JRadioButton jRadioButton52;
private javax.swing.JRadioButton jRadioButton53;
private javax.swing.JRadioButton jRadioButton54;
private javax.swing.JRadioButton jRadioButton55;
private javax.swing.JRadioButton jRadioButton56;
private javax.swing.JRadioButton jRadioButton57;
private javax.swing.JRadioButton jRadioButton58;
private javax.swing.JRadioButton jRadioButton6;
private javax.swing.JRadioButton jRadioButton62;
private javax.swing.JRadioButton jRadioButton63;
private javax.swing.JRadioButton jRadioButton64;
private javax.swing.JRadioButton jRadioButton7;
private javax.swing.JRadioButton jRadioButton8;
private javax.swing.JRadioButton jRadioButton9;
private javax.swing.JTextField jTextField1;
private javax.swing.JTextField jTextField2;
private javax.swing.JTextField jTextField3;
private javax.swing.JTextField jTextField5;
    // End of variables declaration                   
}

